export default {
	defaultLoanRatioType: "Fixe",
	defaultLoanUserCountry: "FR",
	defaultLoanPeriodicity: "mensuel",
	defaultLoanIsProfessional: false,
	defaultLoanFranchiseITT: 6,
	defaultLoanUserIsExpatriate: false,
	defaultLoanTravelsToForeignCountry: false,
	defaultLoanTravelsToRiskyCountry: false,
	defaultLoanWorkRequiresFineTools: false,
	defaultLoanPartTimeTherapeutic: true,
	defaultLoanHospitalizationOption: "YES_WITHOUT_HOSPITALIZATION",
	civility: {
		M: "Monsieur",
		Mme: "Madame"
	},
	maritalStatus: {
		single: "Célibataire",
		married: "Marié(e)",
		pacs: "Pacsé(e)",
		divorced: "Divorcé(e)",
		couple: "Concubin(e)",
		widow: "Veuf/ve",
	},
	occupation: {
		employee: "Salarié(e)",
		executive: "Salarié(e) Cadre",
		farmer: "Salarié(e) / exploitant(e) agricole",
		entrepreneur: "Chef d'entreprise",
		selfEmployed: "Travailleur / Travailleuse non salarié(e)",
		unemployed: "Sans profession",
		functionary: "Fonctionnaire",
		student: "Étudiant(e)",
		retired: "Retraité(e)",
		other: "Autre",
	},
	familyTies: {
		conjoint: "Conjoint / Conjointe",
		child: "Enfant",
		parent: "Parent",
		spouse: "Époux / Épouse",
		other: "Autre",
		myself: "Moi-même",
	},
	loanProjectType: {
		credit_travaux: 'Crédit travaux',
		credit_immobilier: 'Résidence principale',
		credit_immobilier_locatif: 'Bien mis en location',
	},
	loanResumptionType: {
		NEW_LOAN: "Nouveau prêt",
		RESUMPTION: "Reprise immédiate"
	},
	loanType: {
		RELAIS: 'RELAIS',
		AMORTISSABLE: 'AMORTISSABLE',
		PRET_A_PALIER:'PRET_A_PALIER',
	},
	deferralType: {
		TOTAL: 'Total',
		PARTIEL: 'Partiel'
	},
	specificOccupation: {
		AGENT_DE_MAITRISE_CONTREMAITRE: 'Agent de maitrise / contremaître',
		PROFESSIONS_AGRICOLES: 'Professions agricoles',
		ARTISAN: 'Artisan',
		SANS_PROFESSION_ETUDIANT_INTERMITTENT_SAISONNIER: 'Sans profession / Etudiant/ Intermittent / Saisonnier',
		SALARIE_CADRE_ASSIMILE_CADRE_INGENIEUR_HORS_PERSONNEL_NAVIGANT: 'Salarié Cadre/ Assimilé cadre / Ingénieur (hors personnel navigant)',
		DIRIGEANT_DE_SOCIETE_GERANT_CHEF_ENTREPRISE_MOINS_10_ARTISAN_COMMERCANT: "Dirigeant de société/ Gérant/ Chef d'entreprise (de moins de 10 salariés) artisan/commerçant",
		DIRIGEANT_DE_SOCIETE_GERANT_CHEF_ENTREPRISE_MOINS_10_HORS_ARTISAN_COMMERCANT: "Dirigeant de société/ Gérant/ Chef d'entreprise (de moins de 10 salariés) hors artisan/commerçant",
		DIRIGEANT_DE_SOCIETE_GERANT_CHEF_ENTREPRISE_10_ET_PLUS: "Dirigeant de société/ Gérant/ Chef d'entreprise (de 10 salariés et plus)",
		COMMERCANT: 'Commerçant',
		EMPLOYE_BUREAU: 'Employé de bureau',
		SALARIE_NON_CADRE_HORS_EMPLOYE_BUREAU_PERSONNEL_NAVIGANT: "Salarié non cadre (hors employé de bureau & personnel navigant)", // If chosen, must result in a detailed job between the 6 options
		FONCTIONNAIRE_DE_CATEGORIE_A_HORS_ENSEIGNEMENT: "Fonctionnaire de catégorie A (hors enseignement)", // If chosen, must result in a detailed job between the 6 options
		FONCTIONNAIRE_DE_CATEGORIE_B_HORS_ENSEIGNEMENT: "Fonctionnaire de catégorie B (hors enseignement)", // If chosen, must result in a detailed job between the 6 options
		FONCTIONNAIRE_DE_CATEGORIE_C_HORS_ENSEIGNEMENT: "Fonctionnaire de catégorie C (hors enseignement)", // If chosen, must result in a detailed job between the 6 options
		PROFESSEUR_AGREGE: "Professeur agrégé",
		INSTITUTEUR_PROFESSEUR_DES_ECOLES_OU_PROFESSION_ASSIMILEE: "Instituteur, Professeur des écoles ou profession assimilée",
		PROFESSEUR_CERTIFIE_OU_PROFESSION_ASSIMILEE: "Professeur certifié ou profession assimilée",
		PROFESSION_INTERMEDIAIRE_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL: "Profession intermédiaire de la santé et du travail social", // If chosen, must result in a detailed job between the 6 options
		PROFESSION_LIBERALE_MEDICALE_OU_PARAMEDICALE_MEDECIN_OU_INTERNE_GENERALISTE_SPECIALISTE: "Profession libérale médicale ou paramédicale / Médecin (ou Interne) généraliste/ spécialiste", // If chosen, must result in a detailed job between the 5 options
		PROFESSION_LIBERALE_HORS_MEDICAL_PARAMEDICAL: "Profession libérale (hors médical/ paramédical)",
		OUVRIERS_PROFESSIONS_DU_TRANSPORT: "Ouvriers / Professions du Transport",
		HOTESSE_STEWARD_AUTRE_PERSONNEL_NAVIGANT: "Hôtesse, steward, autre personnel navigant",
		CADRE_NAVIGANT_TECHNIQUE_COMMERCIAL: "Cadre navigant technique/commercial",
		RETRAITE_PRE_RETRAITE_CADRE_FONCT_CLASSE_A_CHEF_ENTREPRISE_PROF_LIB: "Retraité, Pré-retraité (Cadre/ Fonct. Classe A/ Chef d'Entreprise/Prof. lib)",
		RETRAITE_PRE_RETRAITE_NON_CADRE: "Retraité, Pré-retraité (non cadre)",
		TECHNICIEN: "Technicien",
	},
	specificOccupationDetails: {
		[this.specificOccupation.FONCTIONNAIRE_DE_CATEGORIE_A_HORS_ENSEIGNEMENT]: {
			FONCTIONNAIRE_DE_CATEGORIE_A_MEDICAL_CHIRURGIEN: "Chirurgiens, chirurgiens-dentistes",
			FONCTIONNAIRE_DE_CATEGORIE_A_MEDICAL_MEDECIN_PHARMACIEN: "Médecins, médecins spécialistes, interne, vétérinaires, pharmacien",
			FONCTIONNAIRE_DE_CATEGORIE_A_MEDICAL_OSTEOPATHE: "Ostéopathes",
			FONCTIONNAIRE_DE_CATEGORIE_A_MEDICAL_PARAMEDICAL: "Sages-femmes, kiné",
			FONCTIONNAIRE_DE_CATEGORIE_A_MEDICAL_AUTRES: "Autres professions médicales / paramédicales",
			FONCTIONNAIRE_DE_CATEGORIE_A_NON_MEDICAL: "Aucune de ces professions",
		},
		[this.specificOccupation.FONCTIONNAIRE_DE_CATEGORIE_B_HORS_ENSEIGNEMENT]: {
			FONCTIONNAIRE_DE_CATEGORIE_B_MEDICAL_CHIRURGIEN: "Chirurgiens, chirurgiens-dentistes",
			FONCTIONNAIRE_DE_CATEGORIE_B_MEDICAL_MEDECIN_PHARMACIEN: "Médecins, médecins spécialistes, interne, vétérinaires, pharmacien",
			FONCTIONNAIRE_DE_CATEGORIE_B_MEDICAL_OSTEOPATHE: "Ostéopathes",
			FONCTIONNAIRE_DE_CATEGORIE_B_MEDICAL_PARAMEDICAL: "Sages-femmes, kiné",
			FONCTIONNAIRE_DE_CATEGORIE_B_MEDICAL_AUTRES: "Autres professions médicales / paramédicales",
			FONCTIONNAIRE_DE_CATEGORIE_B_NON_MEDICAL: "Aucune de ces professions",
		},
		[this.specificOccupation.FONCTIONNAIRE_DE_CATEGORIE_C_HORS_ENSEIGNEMENT]: {
			FONCTIONNAIRE_DE_CATEGORIE_C_MEDICAL_CHIRURGIEN: "Chirurgiens, chirurgiens-dentistes",
			FONCTIONNAIRE_DE_CATEGORIE_C_MEDICAL_MEDECIN_PHARMACIEN: "Médecins, médecins spécialistes, interne, vétérinaires, pharmacien",
			FONCTIONNAIRE_DE_CATEGORIE_C_MEDICAL_OSTEOPATHE: "Ostéopathes",
			FONCTIONNAIRE_DE_CATEGORIE_C_MEDICAL_PARAMEDICAL: "Sages-femmes, kiné",
			FONCTIONNAIRE_DE_CATEGORIE_C_MEDICAL_AUTRES: "Autres professions médicales / paramédicales",
			FONCTIONNAIRE_DE_CATEGORIE_C_NON_MEDICAL: "Aucune de ces professions",
		},
		[this.specificOccupation.SALARIE_NON_CADRE_HORS_EMPLOYE_BUREAU_PERSONNEL_NAVIGANT]: {
			SALARIE_NON_CADRE_MEDICAL_CHIRURGIEN: "Chirurgiens, chirurgiens-dentistes",
			SALARIE_NON_CADRE_MEDICAL_MEDECIN_PHARMACIEN: "Médecins, médecins spécialistes, interne, vétérinaires, pharmacien",
			SALARIE_NON_CADRE_MEDICAL_OSTEOPATHE: "Ostéopathes",
			SALARIE_NON_CADRE_MEDICAL_PARAMEDICAL: "Sages-femmes, kiné",
			SALARIE_NON_CADRE_MEDICAL_AUTRES: "Autres professions médicales / paramédicales",
			SALARIE_NON_CADRE_NON_MEDICAL: "Aucune de ces professions",
		},
		[this.specificOccupation.PROFESSION_INTERMEDIAIRE_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL]: {
			PROFESSION_INTERMEDIAIRE_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL_CHIRURGIEN: "Chirurgiens, chirurgiens-dentistes",
			PROFESSION_INTERMEDIAIRE_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL_MEDECIN_PHARMACIEN: "Médecins, médecins spécialistes, interne, vétérinaires, pharmacien",
			PROFESSION_INTERMEDIAIRE_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL_OSTEOPATHE: "Ostéopathes",
			PROFESSION_INTERMEDIAIRE_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL_PARAMEDICAL: "Sages-femmes, kiné",
			PROFESSION_INTERMEDIAIRE_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL_AUTRES: "Autres professions médicales / paramédicales",
			PROFESSION_INTERMEDIAIRE_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL_NON: "Aucune de ces professions",
		},		[this.specificOccupation.PROFESSION_LIBERALE_MEDICALE_OU_PARAMEDICALE_MEDECIN_OU_INTERNE_GENERALISTE_SPECIALISTE]: {
			PROFESSION_LIBERALE_MEDICALE_OU_PARAMEDICALE_CHIRURGIEN: "Chirurgiens, chirurgiens-dentistes",
			PROFESSION_LIBERALE_MEDICALE_OU_PARAMEDICALE_MEDECIN_PHARMACIEN: "Médecins, médecins spécialistes, interne, vétérinaires, pharmacien",
			PROFESSION_LIBERALE_MEDICALE_OU_PARAMEDICALE_OSTEOPATHE: "Ostéopathes",
			PROFESSION_LIBERALE_MEDICALE_OU_PARAMEDICALE_PARAMEDICAL: "Sages-femmes, kiné",
			PROFESSION_LIBERALE_MEDICALE_OU_PARAMEDICALE_AUTRES: "Autres professions médicales / paramédicales",
		},
	},
	maritalStatusOptions: Object.entries(this.maritalStatus).map(([value, name]) => ({name, value})),
	occupationOptions: Object.entries(this.occupation).map(([value, name]) => ({name, value})),
	familyTiesOptions: Object.entries(this.familyTies).filter(([key]) => key !== "myself").map(([value, name]) => ({name, value})),
	civilityOptions: Object.entries(this.civility).map(([value, name]) => ({name, value})),
	loanTypeOptions: Object.entries(this.loanType).map(([value, name]) => ({name, value})),
	deferralTypeOptions: Object.entries(this.deferralType).map(([value, name]) => ({name, value})),
	loanProjectTypeOptions: Object.entries(this.loanProjectType).map(([value, name]) => ({name, value})),
	loanResumptionTypeOptions: Object.entries(this.loanResumptionType).map(([value, name]) => ({name, value})),
	specificOccupationOptions: Object.entries(this.specificOccupation).map(([value, name]) => ({name, value})),
	getSpecificOccupationDetailsOptions: (specificOccupation) => Object.entries(this.specificOccupationDetails[specificOccupation]).map(([value, name]) => ({name, value})),
	getLoanEffectiveDate: () => dayjs().add(3, 'month').$d,
	// getLoanSignatureDate: () => dayjs().subtract(1, 'year').$d, // Deprecated
}